### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by anna-s-h** [Nandaka/PixivUtil2#1352] opened 2024-07-10 04:39 UTC
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Description

**Things I have already tried**
Resetting the cookie, resetting to an accurate browser agent, changing browser agent to remove everything after "Mozilla/5.0"

**Log file:**

2024-07-10 00:35:15,801 - PixivUtil20240703 - INFO - ###############################################################
2024-07-10 00:35:15,801 - PixivUtil20240703 - INFO - Starting with argument: [PixivUtil2.py].
2024-07-10 00:35:15,801 - PixivUtil20240703 - INFO - Setting log level to: DEBUG
2024-07-10 00:35:15,801 - PixivUtil20240703 - INFO - No default cookie jar available, creating... 
2024-07-10 00:35:15,903 - PixivUtil20240703 - INFO - Using default DB Path: /home/solanum/documents/projects/PixivUtil2/db.sqlite
2024-07-10 00:35:15,903 - PixivUtil20240703 - INFO - Limit up to: 10 page(s).
2024-07-10 00:35:15,903 - PixivUtil20240703 - INFO - Trying to log in with saved cookie
2024-07-10 00:35:16,041 - PixivUtil20240703 - ERROR - Error at doLogin(): (<class 'mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib.error.HTTPError instance) at 0x7fbe7906c8b0 whose wrapped object = <HTTPError 403: 'Forbidden'>>, <traceback object at 0x7fbe790ef400>)
2024-07-10 00:35:16,043 - PixivUtil20240703 - ERROR - Traceback (most recent call last):
  File "/home/solanum/documents/projects/PixivUtil2/PixivUtil2.py", line 1527, in doLogin
    result = __br__.loginUsingCookie()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/solanum/documents/projects/PixivUtil2/PixivBrowserFactory.py", line 351, in loginUsingCookie
    res = self.open_with_retry('https://www.pixiv.net/en')  # + self._locale)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/solanum/documents/projects/PixivUtil2/PixivBrowserFactory.py", line 207, in open_with_retry
    res = self.open(url, data, timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/solanum/documents/projects/PixivUtil2/.venv/lib/python3.11/site-packages/mechanize/_mechanize.py", line 257, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/solanum/documents/projects/PixivUtil2/.venv/lib/python3.11/site-packages/mechanize/_mechanize.py", line 313, in _mech_open
    raise response
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 403: Forbidden

2024-07-10 00:35:16,043 - PixivUtil20240703 - ERROR - Cannot Login!
2024-07-10 00:35:17,498 - PixivUtil20240703 - INFO - EXIT: 0
2024-07-10 00:35:17,498 - PixivUtil20240703 - INFO - ###############################################################

### Versions
20240703

**Comment by Gin-no-kami** [comment] 2024-07-10 13:38
I am having the same issue as above and have also followed the steps they outlined to fix the problem. I have also tried waiting over 24 hours between logins to see if that would fix anything.

**Comment by levipl** [comment] 2024-07-10 18:11
Me too have same issue.
Problem doesn't exist on Windows, but when using Docker on Linux ends with error.

**Comment by vampiricwulf** [comment] 2024-07-11 05:28
403 error, properly copied my useragent and cookies.
However, I am using Windows and not Docker.

**Comment by zhangxt-ihep** [comment] 2024-07-13 17:26
Pivix seems to start forbid directly accessing to 'https://www.pixiv.net/en/' some days ago.
@vampiricwulf @Gin-no-kami @anna-s-h @levipl, maybe you could try my temporary solution, it works in myside:
1. Open the `PixivUtil2/PixivBrowserFactory.py` file in your editor.
2. In line 351, replace `https://www.pixiv.net/en/` with `https://www.pixiv.net/`
3. In line 372, replace `https://www.pixiv.net/` with `https://www.pixiv.net`
4. **Important**: Open Pixiv index webpage in your browser and ensure your Pixiv index webpage language is **not** English. You can choose Japanese or Chinese for example.

Then you can try to download some artworks by PixivUtil2. If everything goes smoothly, it will not meet this login issue any more.

**Comment by Gin-no-kami** [comment] 2024-07-13 17:38
@zhangxt-ihep Your solution worked! Hopefully you can get a PR merged to fix it for everyone.

**Comment by zhangxt-ihep** [comment] 2024-07-13 18:45
@Gin-no-kami , I think the problem is because that Pixiv closed the accessibility to ‘https://www.pixiv.net/en/' request with only PHPSESSID cookie. What's more, if you are using Pixiv webpage in English, you could not access ‘https://www.pixiv.net/' with only PHPSESSID cookie request neither. To prove this, you could try to keep Pixiv webpage in English in step 4 of my solution, then you will get the same login issue when you try downloading artworks.

I have no idea about why Pixiv made this. Maybe Pixiv wants to merge all index to ‘https://www.pixiv.net/' without any locations or just keeps English access safer. The only thing I know is that the other languages are still accessible by PHPSESSID cookies.

So, if I merge my temporary solution, the users in English need to switch their language to other languages every time they want to use PixivUtil2. I don't think it is a good solution for them to use PixivUtil2, but I don't know how to make a better way. So I can only raise this problem and wait for devleopers to solve it.

**Comment by levipl** [comment] 2024-07-13 19:32
@zhangxt-ihep I can confirm that you solution works!

**Comment by vampiricwulf** [comment] 2024-07-14 01:15
@zhangxt-ihep That worked for me as well!
I don't need to constantly swap locale either since I generally use: https://github.com/ppixiv/ppixiv which has everything in English regardless of locale.

**Comment by rizelbr** [comment] 2024-07-14 12:48
@zhangxt-ihep 
My Pixiv language is Japanese, but was still having issues with PixivUtil.

Can confirm your temporary solution is working (at least so far).

**Comment by zhangxt-ihep** [comment] 2024-07-15 01:12
@rizelbr, only webpage language being Japanese is not enough. The PixivUtil2 access English pages in default, so the step 2 in my solution changes the locale. In general, to solve this issue, you need to avoid all possible access to English pages of Pixiv (which means both step 2 and step 4).

**Comment by beterhans** [comment] 2024-07-16 16:51
doesn't work for me

Reading /Users/hans/Documents/source_code/python/PixivUtil2/config.ini ...
Configuration loaded.
2 of 2s.  rror [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)> 1 
2 of 2s.  
2 of 2s.  

    return self.do_open(conn_factory, req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/mechanize/_urllib2_fork.py", line 1246, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hans/Documents/source_code/python/PixivUtil2/PixivUtil2.py", line 1779, in <module>
    main()
  File "/Users/hans/Documents/source_code/python/PixivUtil2/PixivUtil2.py", line 1632, in main
    PixivHelper.check_version(__br__, config=__config__)
  File "/Users/hans/Documents/source_code/python/PixivUtil2/PixivHelper.py", line 1293, in check_version
    result = br.open_with_retry("https://raw.githubusercontent.com/Nandaka/PixivUtil2/master/PixivConstant.py", retry=3)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hans/Documents/source_code/python/PixivUtil2/PixivBrowserFactory.py", line 226, in open_with_retry
    PixivHelper.print_delay(2)
  File "/Users/hans/Documents/source_code/python/PixivUtil2/PixivHelper.py", line 745, in print_delay
    time.sleep(1)
KeyboardInterrupt

**Comment by zhangxt-ihep** [comment] 2024-07-17 01:22
@beterhans the problem you met doesn't seem to be caused by this issue. Please check the Pixiv URL in your code is corrected and your local CA path is up-to-date.

**Closed** 2024-08-22 00:42 UTC

**Comment by beterhans** [comment] 2024-11-15 04:27
> @beterhans the problem you met doesn't seem to be caused by this issue. Please check the Pixiv URL in your code is corrected and your local CA path is up-to-date.

Thanks I found out why

on MacOS getting this issue.
you need to install certificate on MacOS

by run
Install Certificates.command
Update Shell Profile.command
under
Python installed folder mine is /Application/Python3.12
