### ISSUE TITLE
Forward slashes in filename format options incorrectly sanitized on Windows

### ISSUE THREAD

**Issue by alexwh** [Nandaka/PixivUtil2#645] opened 2020-03-01 18:38 UTC
### Prerequisites

* [x] Did you read FAQ section?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?

### Description
Running Pixivutil on a Linux system initally, then using the same config on a Windows box results in filename*format options with a forward slash instead of a backward slash.

During download, this forward slash will be incorrectly sanitized into an underscore by [sanitize_filename()](https://github.com/Nandaka/PixivUtil2/blob/b03944aacd4847914c633720bd6fa804ce9ad978/PixivHelper.py#L63).

For what it's worth, Windows can handle forward slash path seperators just fine:

```
>>> with open("test\\file.txt", "w") as f:
...   f.write("hi")
...
2
>>> with open("test/file.txt", "w") as f:
...   f.write("hi")
...
2
```

From my limited perspective, you can either:
- Use "/" everywhere, though grepping for os.sep has a lot of results, and this may affect other code outside of the filename formatting.
- Replace the forward slashes with backward ones when running on Windows in `make_filename()` before any template transforms take place.
- Remove the platform specific regex for Windows in sanitize_filename, as forward slashes not in the format string itself should already be taken care of by replace_path_seperator in `make_filename()`

Additionally, os.path.join [should be preferred](https://docs.python.org/3/library/os.html#os.sep) over manually concatting strings with os.sep.

### Steps to Reproduce

1. Run Pixivutil on Windows with the default Linux filenameformat options (`filenameformat = %artist% (%member_id%)/%urlFilename% - %title%`)

**Expected behavior:** File to be placed in a folder

**Actual behavior:** File placed in download directory root

### Versions
20200228

**Comment by alexwh** [comment] 2020-03-01 19:52
This also seems to affect `createmangadir`.

**Comment by Nandaka** [comment] 2020-03-03 15:41
by design, I don't want to create subdirs if the title got forward/backward slash in it.

**Comment by alexwh** [comment] 2020-03-03 15:54
Yes, but slashes within the config file should not be sanitized.

**Comment by Nandaka** [comment] 2020-03-04 13:42
maybe you can send a pull request?

**Comment by alexwh** [comment] 2020-03-06 01:05
I made #647.

**Comment by Nandaka** [comment] 2020-03-09 02:22
merged

**Closed** 2020-04-05 07:19 UTC
Labels: Enhancement
