### ISSUE TITLE
[Feature Request] Option to re-encode downloaded images for storage space optimization

### ISSUE THREAD

**Issue by smol-loli** [Nandaka/PixivUtil2#1215] opened 2022-12-21 15:22 UTC
### Prerequisites

* [x] Did you read FAQ section in [readme.md](https://github.com/Nandaka/PixivUtil2/blob/master/readme.md)?
* [x] Did you test with the latest [releases](https://github.com/Nandaka/PixivUtil2/releases "latest releases") or [commit](https://github.com/Nandaka/PixivUtil2/commits/master "latest commit") ?
* [x] Did you search for existing issues in [Issues](https://github.com/Nandaka/PixivUtil2/issues)?

### Feature Request

Option to re-encode downloaded images (png, jpg) with self-defined encoding options. Would be nice to re-encode already existing images and also re-encoding newly downloaded files directly to safe space.

I saved ~ 1.6 GB by re-encoding 6.420 png files with compression set to 9 (highest compression):

21.062.589.361 Bytes PNG before
19.403.317.933 Bytes PNG after
Overall storage space saved: ~ 1.6 GB

I don't know if this is practical to implement, I'm sorry if this idea is stupid :)

**Comment by cglmrfreeman** [comment] 2022-12-23 03:51
I think that was done in commit https://github.com/Nandaka/PixivUtil2/commit/3b66f073045e7bd1b609519a9878d1116971f051 ?
Unless you had something more specific in mind?

**Comment by smol-loli** [comment] 2022-12-23 19:54
I know that it's possible to re-encode ugoria. What I meant was an option to also re-encode normal images. You get what I try to say?

**Comment by cglmrfreeman** [comment] 2022-12-23 20:07
Oh I misunderstood. I now feel that's a feature that falls outside the scope of PixivUtil2, and you'd also need a separate database/flag to not re-encode already re-encoded images. Scanning the database within a python script and then executing your own image utility (trimage maybe?) isn't terribly difficult to do on your own. Also I feel if you accidentally left `alwaysCheckFileSize` to `true` in your config, you will just reset all that space.

Also, there's the undocumented `postProcessingCmd` option in `config.ini`. From changelog:
>- Implement #970: add feature to perform post processing for downloaded files.
>  Add config in [DownloadControl] section:
>  - enablePostProcessing = default False. Set to true to enabled post processing cmd for every downloaded files
>  - postProcessingCmd = command to execute. add %filename% to pass the downloaded filename.
>    NO ERROR HANDLING AT ALL, use on your own risk.

So `postProcessingCmd = trimage %filename%` might work.

So really this may be more of a duplicate of #970

**Comment by smol-loli** [comment] 2022-12-23 20:16
>  Also I feel if you accidentally left `alwaysCheckFileSize` to `true` in your config, you will just reset all that space.

Thanks for the tip but I was smart enough to disable that.

> Also, there's the undocumented `postProcessingCmd` option in `config.ini`. From changelog:
> 
> > * Implement [Feature Request: Compressing images after downloading #970](https://github.com/Nandaka/PixivUtil2/issues/970): add feature to perform post processing for downloaded files.
> >   Add config in [DownloadControl] section:
> > * enablePostProcessing = default False. Set to true to enabled post processing cmd for every downloaded files
> > * postProcessingCmd = command to execute. add %filename% to pass the downloaded filename.
> >   NO ERROR HANDLING AT ALL, use on your own risk.
> 
> So `postProcessingCmd = trimage %filename%` might work.

Thats interesting, didn't know this existed. I'll try to do the re-encoding with that. Sorry for bothering you!

**Closed** 2022-12-23 20:17 UTC

**Comment by cglmrfreeman** [comment] 2022-12-23 20:20
> Thats interesting, didn't know this existed. I'll try to do the re-encoding with that. Sorry for bothering you!

No bother to me at all! I didn't know this existed either until I just wondered if it had any kind of post-processing and found it in the change logs! Hope this helped, cheers and happy holidays!
